"""initial migration

Revision ID: 6b63e47d514f
Revises: 
Create Date: 2022-04-07 16:35:11.828579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b63e47d514f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('transactions', sa.Column('amount', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'amount')
    op.drop_column('transactions', 'date')
    # ### end Alembic commands ###
